### ISSUE TITLE
version 19.8.5 causes TypeError: object.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by hixus** [i18next/i18next#1542]
## 💥 Regression Report

version 19.8.5 causes TypeError: object.hasOwnProperty is not a function when calling t-function.

## Last working version

Worked up to version: 19.8.4

Stopped working in version: 19.8.5

## To Reproduce

This is my config which works with old version.
```js
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import * as dev from "../locales/dev.json";
import * as fi from "../locales/fi.json";

i18n
  .use(initReactI18next) 
  .init({
    resources: { fi, dev },
    lng: "fi",
    ns: ["default"], 
    defaultNS: "default",
    debug: true,
    keySeparator: false,
    interpolation: {
      escapeValue: false, 
    },
  });

export default i18n;
```

## Expected behavior

T-function should work without throwing.

```js
i18n.t('hello') // should not throw TypeError: object.hasOwnProperty is not a function 
```

## Your Environment

- *runtime version*: i.e. node v14
- *i18next version*: i.e. 19.8.5 (react-i18next 11.8.5)
- *os*: Mac

**Comment by adrai** [comment]
Not able to reproduce it.
Can you create a reproducable example? Maybe directly on codesandbox?

**Comment by AdirAmsalem** [comment]
@adrai I saw you pushed a fix but our app still breaks with the new version.
Any chance it wasn't fully fixed? (the code attached uses `i18next-react` as well)
![image](https://user-images.githubusercontent.com/2660550/106563021-d834ab80-6533-11eb-89dc-8bdf48be3898.png)

**Comment by adrai** [comment]
@AdirAmsalem still waiting to be able to reproduce your issue...

**Comment by AdirAmsalem** [comment]
@adrai for us (I'm not with @hixus so maybe his issue is different) it fails specifically in tests, with the following configuration:
https://codesandbox.io/s/cool-noyce-xl9f3?file=/src/App.js

You can see that with `i18next@19.8.4` it works, but if you'll change it to `i18next@19.8.6` it'll fail.

I suspect it's related to the usage of `Proxy` here:
```js
i18n.init({
  resources: new Proxy({}, { get: (_target, name) => name })
});
```
We do it for something in our tests that allows us to validate the output etc in a customized way (for `t('key', options)`).

Btw,  I know there's `cimode` which is similar, but this one allows us to do something more advanced which also includes the `options` etc.

Hope this helps, and thanks for your time!

**Comment by adrai** [comment]
Should be fixed with v19.8.7
