### ISSUE TITLE
TypeScript Error TS2558 after upgrade to v23: Expected 3-4 type arguments, but got 1

### ISSUE THREAD

**Issue by adrianui5** [i18next/i18next#2029]
Hello,

I was using this implementation of i18next for my react components:
this.props.t!<string>("test_page.area")

Now after upgrading to version 23.0.0, I am facing this issue:
Type 'TOpt["returnObjects"] extends true ? $SpecialObject : string' is not assignable to type 'ReactI18NextChildren'.
  Type 'string | $SpecialObject' is not assignable to type 'ReactI18NextChildren'.
    Type 'object' is not assignable to type 'ReactI18NextChildren'.
      Type 'TOpt["returnObjects"] extends true ? $SpecialObject : string' is not assignable to type 'ReactPortal'.ts(2322)
index.d.ts(47, 5): The expected type comes from property 'children' which is declared here on type 'DetailedHTMLProps<TdHTMLAttributes<HTMLTableDataCellElement>, HTMLTableDataCellElement>'
Expected 3-4 type arguments, but got 1.ts(2558)

When removing the <string>, I am ending up with an eslint issue:
Forbidden non-null assertion

Now I am asking myself, how do I need to change my coding to meet the new syntax requirements?

Thanks,
Adrian

**Comment by adrai** [comment]
Make sure you updated not only i18next but also react-i18next.
Please provide a minimal reproducible example repository or codsandbox example or similar.

**Comment by pedrodurek** [comment]
@adrianui5, Could you share a reproducible example?
