### ISSUE TITLE
Mismatch between TypeScript types and CommonJS export

### ISSUE THREAD

**Issue by stevendesu** [i18next/i18next#1447]
After [disabling an ESLint rule that was causing me trouble](https://github.com/i18next/i18next/issues/1446), I ran into a new issue trying to incorporate i18next into my project.

I'm writing code for a back-end NodeJS server that is compiled with TypeScript. Therefore the `import` syntax is handled not by Babel, but by TypeScript - and gets translated as such:

```
import i18next from "i18next";

// Becomes:

const i18next_1 = require("i18next").default;
```

This output JavaScript is then run in NodeJS like normal, relying on the `main` key in the `package.json` to locate the module. Thus it loads `./dist/cjs/i18next.js`, which exports like so:

```
//...

var i18next = new I18n();

module.exports = i18next;
```

As you can see, there's no export called "default". Therefore what I really need is to import the `module.exports` under the name i18next. This can be done in TypeScript:

```
import * as i18next from "i18next";
```

However when I do this, I start getting errors whenever I try to use it:

![Screen Shot 2020-05-07 at 4 24 06 PM](https://user-images.githubusercontent.com/1384974/81341244-36089580-907f-11ea-9233-4c569cb52a63.png)

Worse yet, since these are **TypeScript errors** and not ESLint errors, I can't just hand-wave them or disable them. Attempting to run `tsc` against my code stops compilation early with the error:

```
stevenbarnett@MacBook-Pro bf-hapijs-plugin % npx tsc
src/i18n/index.ts:33:35 - error TS2339: Property 'init' does not exist on type 'typeof import("/Users/stevenbarnett/Repos/pangolin-jerky/bf-hapijs-plugin/node_modules/i18next/index")'.

33      const translate = await i18next.init({
                                        ~~~~


Found 1 error.
```

For the record, if I **don't** try to import i18next this way (using `import * as ...`) then the following happens:

```
import i18next from "i18next";

console.log(i18next); // -> undefined

i18next.init(); // -> crashes with error "Cannot read property 'init' of undefined"
```

**Comment by jamuhl** [comment]
keeping this open for TS users that might help out here

**Comment by stevendesu** [comment]
There  is a slightly ugly work-around -- reverting to CommonJS require statements instead of ES6 import statements:

```
const i18next = require("i18next");
```

This works with the TypeScript definitions, compiles properly, and runs

**Comment by mjbcopland** [comment]
Caused by #1352?

**Comment by TrySound** [comment]
Try to enable esModuleInterop.

**Comment by stevendesu** [comment]
I'll have to read up on what `esModuleInterop` does. I tried enabling it and re-running my unit tests but enabling that feature in my tsconfig broke several other things.

**Comment by mjbcopland** [comment]
> I'll have to read up on what `esModuleInterop` does

Adds a runtime check to allow importing non-ESM packages as default imports. i18next claims to have a default export, so that is how you must use it with TypeScript, but does not actually have one, so will error at runtime without this check.

#1352 broke support for `esModuleInterop: false` and at the same time removed the tests for it.

**Comment by rosskevin** [comment]
#1352 has the full explanation, this has been fully researched and reasons explained therein.

Commonjs has no concept of default export, therefore if you want to use a commonjs package/loader, you MUST use `esModuleInterop: true`, designed exactly for this situation.

**Comment by mjbcopland** [comment]
@rosskevin the fact of the matter is that in its current state, i18next with `esModuleInterop: false` is broken. I see that #1458 is not correct for the current approach, but I don't believe that _"you MUST use `esModuleInterop: true`"_ is a valid solution.

> I spent four hours on this and documented my findings yesterday in https://github.com/rosskevin/test-i18next/tree/non-esmoduleinterop-ts-loader

> This repo is a full explanation with a working example of `esModuleInterop: false`

That example project uses i18next v18 which uses the namespace/`export =` approach and, as stated, works. Upgrading i18next to v19 and using `export default` breaks everything.

[DefinitelyTyped would suggest that `export =` is correct](https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default), but we know that we're [using ESM default exports](https://github.com/i18next/i18next/blob/8e1fb28/src/index.js#L3) so let's assume that our `export default` definition is correct.

The first error is that TypeScript complains; `Property 'use' does not exist on 'typeof import("i18next")'`. As per #1352, _"these breakages are expected and intended"_, so let's update our imports accordingly.

```diff
diff --git a/src/app/i18n.ts b/src/app/i18n.ts
index 5d7e4dc..d213d49 100644
--- a/src/app/i18n.ts
+++ b/src/app/i18n.ts
@@ -5 +5 @@ import { appStrings } from '../../assets/i18n/appStrings.json'
-import * as i18n from 'i18next'
+import i18n, { TFunction } from 'i18next'
@@ -23 +23 @@ i18n.use(initReactI18next).init(
-  (err: Error, t: i18n.TFunction) => {
+  (err: Error, t: TFunction) => {
```

Now TypeScript is happy but we encounter runtime errors; `TypeError: Cannot read property 'use' of undefined`. We are using ESM default exports, so it makes sense that the type declaration reflects this, so why does it error at runtime? Why is the ES Module not reflected in the compiled UMD/CommonJS output?

`dist/cjs/i18next.js` exports like so

```js
module.exports = i18next;
```

but we should be seeing something like this ([as `useESModules` is disabled](https://babeljs.io/docs/en/babel-plugin-transform-runtime#useesmodules))

```js
exports.__esModule = true;

exports.default = i18next;
```

Furthermore, if we edit the relevant files in node_modules as such, everything works perfectly. Is this an issue with the build rather than the types?

Note that fixing the build will affect anyone using CommonJS imports, namely `require('i18next')` will become `require('i18next').default`, but this is a change that should have been expected when migrating to an ESM approach.

**Comment by TrySound** [comment]
`esModuleInterop: false` is wrong at least because it does not follow spec. Users forced to import functions as namespace objects.
```
import * as func from './func';
func() // this should be an object, not a function
```

**Comment by mjbcopland** [comment]
Do you have an example of that? I see `This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.`

Instead something like this works, as described [in the docs](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require)

```ts
import func = require('./func');
func(); // correctly typed as a function
```

Followup from above: using `output.exports: "named"` in the Rollup config gives correct `__esModule`/`exports.default` output.

**Comment by rosskevin** [comment]
> @rosskevin the fact of the matter is that in its current state, i18next with esModuleInterop: false is broken.

It is not, everything typechecks in this repository, both with and without `esModuleInterop`.  I think you are conflating types with loaders.  Types and loaders must work together for the specific module packing type in and interoperable way, this is up to the user to configure specific to their environment.

> I see that #1458 is not correct for the current approach, but I don't believe that "you MUST use esModuleInterop: true" is a valid solution.

As mentioned in #1351, if you want to use an esm module packaged as commonjs you must use `esModuleInterop: true` as _recommended_ by the typescript team https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop

> That example project uses i18next v18 which uses export = and, as stated, works.

You miss the point entirely.  With it as it was in v18, we had a consistent stream of issues filed that were effectively `typescript import does not work` in this and other i18next projects.  Since the change in #1352, we do not have that problem.  

The point of the example repo was for me to setup, from scratch, all the typical tooling to get imports working correctly with the old `export =` style so I could make an informed decision.  It took me hours to get it right, and let's just say I have a better than average understanding of typescript.

The fact that we don't have these issues `typescript import does not work` filed anymore is evidence that the current approach is better for the majority of the community.

> We are using ESM default exports, and it makes sense that the type declaration reflects this, so why does it error at runtime?

Because commonjs packaging has no concept of default exports.

> Why is the ES Module not reflected in the compiled UMD/CommonJS output?

This I do not know, but @TrySound knows much more about rollup and module types on this note.

---
Bottom line: 

1. ESM modules are the way forward and i18next is an ESM module.  
2. Use of commonjs packages with typescript  [is recommended to use esModuleInterop _by the typescript team_](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop).  
3. The current typescript code in this repository works both with and without `esModuleInterop` on, and the user's selection of toolchain/loaders is out of context from this codebase.

The current choices work for most users - and that's what we need to target.

If there is an improvement to be made based on new information or build tooling configuration - let's do it by all means.  But, we will not be going back to a the state that v18 was for the very reasons outlined in #1351.

**Comment by mjbcopland** [comment]
> The fact that we don't have these issues `typescript import does not work` filed anymore

Other than the issue you're currently commenting on? ;)

---

I originally looked at this because I wanted to be able to use `i18next` as a namespace like in previous versions (sidenote: I'm curious why you "always wanted to get rid of [it]") and thought that it would also fix the above issue.

I was basing my information on the runtime cjs code, not the source esm. Now that I see that we're defining the types according to the source, I am happy with their current state. However, that still leaves the issue that they don't match the cjs output.

---

Bottom line:

1. Agree
2. Recommended != required
3. This repository only typechecks typescript code, it doesn't actually run or test any of it. The provided types aren't correct for what happens at runtime.

---

I suspect the headaches were coming from the fact that cjs and esm versions have different interfaces. The cjs version uses `module.exports = i18next` which corresponds to `export =`, the esm version uses `export default i18next`. If you fix the types for one, you'll break them for the other.

The fact that using `export default` has reduced the frequency of these issues is probably because most people are either already using `esModuleInterop: true` or are using a loader/environment which supports ES modules, so use the correctly-typed esm version.

If, however, you happen to be using neither then you'll run into problems as outlined in this thread. Here's a very minimal example.

```ts
import i18next from "i18next";
i18next.init();
```
```json
{
  "compilerOptions": {
    "esModuleInterop": false
  }
}
```
```
$ ts-node .

/Users/michael/Desktop/test-esModuleInterop/index.ts:2
i18next.init();
        ^
TypeError: Cannot read property 'init' of undefined
```

If we transpile the code we can see what's going on.

```js
var i18next_1 = require("i18next");
i18next_1["default"].init();
```

Notice how it's trying to access `i18next_1["default"]` because we've (correctly) told TypeScript that we have a default export. This value is actually `undefined` because in the cjs output we export the object directly as `module.exports = i18next` _not_ `module.exports.default = i18next`.

From Rollup:

https://rollupjs.org/guide/en/#preservemodules

> Note that when transforming to `cjs` or `amd` format, each file will by default be treated as an entry point with `output.exports` set to `auto`. This means that e.g. for `cjs`, a file that only contains a default export will [assign] the value directly to `module.exports`.

https://rollupjs.org/guide/en/#outputexports

> [`output.exports`] defaults to `auto`, which guesses your intentions based on what the `input` module exports.

This guess appears to be incorrect for i18next; as mentioned above, using `exports: "named"` correctly outputs __esModule/default exports in the cjs file and fixes the issue _without_ changing the type declaration, which we've agreed is correct.

**Comment by rosskevin** [comment]
I feel like we are rehashing/restating things that have already been stated, so here is my last shot at this.

> I originally looked at this because I wanted to be able to use i18next as a namespace like in previous versions (sidenote: I'm curious why you "always wanted to get rid of [it]") and thought that it would also fix the above issue.

I wanted to get rid of it because namespaces never caught on.  They are not present in the source are not a concept to be carried forward.  The types should be as close to source as possible.  

> Other than the issue you're currently commenting on? ;)

It is as expected.  This change was made 7 months ago, and zero issues.  This issue is the expected outlier, someone that wants cjs first, which is not as we have chosen.

> I was basing my information on the runtime cjs code, not the source esm.

CJS is clearly not the module packaging path now and moving forward, yet you continue to base your argument from that direction.

> Recommended != required

You also don't have to use typescript.  I recommend it but it is not required.  Design choices must be made, and ESM-first is our design decision.  The easy backwards compatibility solution built by the typescript team for this very situation is `esModuleInterop: true`, and that in-built mechanism good enough for me.  If you have an argument with that, I suggest you make that argument in the typescript repository (I suggest that the next major ts release has interop as the default behavior instead of legacy behavior).

> I suspect the headaches were coming from the fact that cjs and esm versions have different interfaces. The cjs version uses module.exports = i18next which corresponds to export =, the esm version uses export default i18next. If you fix the types for one, you'll break them for the other.

I detailed exactly this in #1351.  We chose to define as an ESM module and type it as that choice.  Runtime toolchain (loading cjs) is out of scope of the source types.  The source types mirror the runtime code, that is all.

> If, however, you happen to be using neither then you'll run into problems as outlined in this thread.

Which is exactly intended and outlined in the text of #1352.  You are the exception as proven by the number of issues filed.  If you want to fight `esModuleInterop` for some reason, that is your choice, but we provide a typescript-team approved method of typechecking and compatible loading.  If you want to live outside the greater than 80% of cases, you are on your own.

> This guess appears to be incorrect for i18next; as mentioned above, using exports: "named" correctly outputs __esModule/default exports in the cjs file and fixes the issue without changing the type declaration, which we've agreed is correct.

If you have a change for rollup that meets the ESM-first expectations I have outlined and helps out CJS users - GREAT!  Please PR that and we will take a look.

**Comment by adrai** [comment]
Sorry guys for the intrusion...
I've no clue about TypeScript, but I have a shy question: "ould a different cjs dist be helpful?
Please have a look at: https://github.com/i18next/i18next/issues/1448#issuecomment-625728909
> https://github.com/i18next/i18next/compare/node-esm
the dist folder would look like this: [dist.zip](https://github.com/i18next/i18next/files/4598174/dist.zip)

**Comment by mjbcopland** [comment]
I feel like we're arguing parallel viewpoints here. I don't disagree except for one thing

> The source types mirror the runtime code, that is all.

The source types do not mirror the commonjs runtime code because of this default export discrepancy.

@adrai That is exactly what I'm talking about. Notice how when you use Babel directly it's using `__esModule` and `exports.default`. This is what's missing from the current Rollup output.

Using `output.exports` in Rollup is one way of fixing it, but will break existing pure-cjs imports. Baking the Babel interop into the code looks like it will support both, so your proposal is probably a better solution.

**Comment by adrai** [comment]
> Baking the Babel interop into the code looks like it will support both, so your proposal is probably a better solution.

Can this be verified by one of you TypeScript pros? ;-)

**Comment by rosskevin** [comment]
> I feel like we're arguing parallel viewpoints here. I don't disagree except for one thing
>
>The source types mirror the runtime code, that is all.
>
>The source types do not mirror the commonjs runtime code because of this default export discrepancy.

When I refer to types, that means `.ts`.  When I refer to runtime code that refers to `.js`.  CJS and ESM refer to a module package, as does ESM. 

I am sorry for not being so clear that it could not be misinterpreted.

The source types mirror the source code, that is all.

**Comment by rosskevin** [comment]
@adrai - sorry, I don't have an answer to your question.  I'd listen to @TrySound specifically on that one.

In general though, I am not a fan of baking in interop code.  I would thing there is a way to config this via rollup to get the same result (and any future bug fixes/upgrades).  But I'll leave it to someone else to advise on the specifics of the module packaging.

**Comment by mjbcopland** [comment]
> The source types mirror the source code, that is all.

Agreed (mostly, for example #1366 is wrong, but perhaps I'll concede to your better than average understanding of typescript).

However, the source code does not mirror the runtime code. Ergo the source types do not mirror the runtime code. If this is deliberate, fine, but it looks like an oversight.

Transforming ES modules to CommonJS should define an `__esModule` property and assign default exports to `exports.default`. This may be just my opinion, but is also how Babel and TypeScript handle it. This is __not__ how Rollup is currently transforming the code for i18next.

That is all.

**Comment by rosskevin** [comment]
> Agreed (mostly, for example #1366 is wrong, but perhaps I'll concede to your better than average understanding of typescript).

#1366 is not part of this conversation.  If there is a bug in the type definitions, PR a fix.  Please stay on topic.

> However, the source code does not mirror the runtime code. Ergo the source types do not mirror the runtime code. If this is deliberate, fine, but it looks like an oversight

I do not know why you continue on with this.  The source types are intended to mirror the source code as I have unequivocally clarified and always intended.  PACKAGING AND PACKAGE LOADING are NOT the same as source (code or types).  It is very deliberate that source types and source code look alike, and very deliberate that we leave the rest to the ecosystem (rollup, babel, node, webpack, etc).  I don't know how I can more clearly state this.  This is why I documented everything in #1352 and #1352.

> Transforming ES modules to CommonJS should define an __esModule property and assign default exports to exports.default

If it is important to you, make it so.  PR it.  If it does not conflict with the stated goals of the project, and I don't see how it does, it will be accepted.
