### ISSUE TITLE
i18next@23.7 sneakily breaks building with older typescript versions

### ISSUE THREAD

**Issue by kcaswick** [i18next/i18next#2090]
## 💥 Regression Report

Dependencies on i18next@^23.4 now install 23.7.10, causing tsc to fail with error:
```log
node_modules/i18next/typescript/t.v4.d.ts:103:69 - error TS1005: '?' expected.
```

This was discovered when first installing a package which depends on i18next, and at first was thought to be a dependency conflict of the direct dependency, since it worked fine in another project.

## Last working version

Worked up to version: 23.6.0

Stopped working in version: 23.7.0

## To Reproduce

- In a clone of i18next: (tested with checkouts of both v23.6.0 and master)
- `cd .\examples\typescript\`
- `npm i typescript@4.5.5`
- `npm run build`

```log
> npm run build

> typescript-example@1.0.0 build
> tsc

node_modules/i18next/typescript/t.v4.d.ts:103:69 - error TS1005: '?' expected.

103   : _FallbackNamespace extends (infer UnionFallbackNs extends string)[]
                                                                        ~


Found 1 error.
```

## Expected behavior

npm to select a compatible version of i18next or report a dependency conflict with typescript

npm run build to succeed

```log
> npm run build

> typescript-example@1.0.0 build
> tsc
```

## Your Environment

- *runtime version*: Node v16.20.1
- *i18next version*: 23.7.10
- *os*: Windows

**Comment by adrai** [comment]
Feel free to provide a PR if you know how to address this...

**Comment by kcaswick** [comment]
I do not offhand. Most likely a tweak to the special t.v4.d.ts that was added for backwards compatibility is a good idea.

I think last time I tried, npm did not have a good way to express "this dependency is optional, but if you use it, use at least 4.7".

We're using the workaround of overriding to i18next 23.6.0.

**Comment by adrai** [comment]
I just tried something with v23.7.11

**Comment by kcaswick** [comment]
That fixed it! Thank you very much!
