### ISSUE TITLE
t.v4.d.ts:189:47 - error TS1005: '?' expected

### ISSUE THREAD

**Issue by maxkomarychev** [i18next/i18next#2152]
## 💥 Regression Report

A clear and concise description of what the regression is.

A project compiled with typescript 4.2.4 throws the following error:

```
node_modules/i18next/typescript/t.v4.d.ts:189:47 - error TS1005: '?' expected.

189     ? Key extends `${infer NKey extends number}`
                                                  ~
```

## Last working version

The truth is I don't really know if it ever worked but I assume so based on similar issue in the past https://github.com/i18next/i18next/issues/2090

Worked up to version: X.X.X

Stopped working in version: Y.Y.Y

## To Reproduce

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the results here
```

## Your Environment

- *runtime version*: i.e. node 18
- *i18next version*: i.e. 23.10.0 and 23.5.1
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
update your TS version to be > v4.9.x

**Comment by zhulien-ivanov** [comment]
Same problem.

i18next: 23.10.1
typescript: 5.4.3

**Comment by sarakhosropour** [comment]
I have the same problem. No solution?

**Comment by adrai** [comment]
Provide a minimal reproducible example repository

**Comment by camilosw** [comment]
I have the same issue with typescript 4.3.5. After checking with multiple versions, I found that the minimum version to solve it is 4.7.x. I updated to 4.7.4 and now it works fine.

**Comment by ParallelUniv3rse** [comment]
Return of the issue #2090. Probably got broken by 0aef924.

**Comment by adrai** [comment]
stale... closing for now...
