### ISSUE TITLE
tsc fails since arrays of strings have been made readonly

### ISSUE THREAD

**Issue by mlegait** [i18next/i18next#1630]
## 💥 Regression Report

I'm working on a project depending on `i18next` and `i18next-http-backend`. Since I updated `i18next` to the version 20.3.4, `tsc` fails:
```
> tsc -d --emitDeclarationOnly --noEmit false --allowJs false --declarationDir lib

node_modules/i18next-http-backend/index.d.ts:108:3 - error TS2416: Property 'create' in type 'I18NextHttpBackend' is not assignable to the same property in base type 'BackendModule<BackendOptions>'.  Type '((languages: string | string[], namespace: string, key: string, fallbackValue: string) => void) | undefined' is not assignable to type '((languages: readonly string[], namespace: string, key: string, fallbackValue: string) => void) | undefined'.
    Type '(languages: string | string[], namespace: string, key: string, fallbackValue: string) => 
void' is not assignable to type '(languages: readonly string[], namespace: string, key: string, fallbackValue: string) => void'.
      Types of parameters 'languages' and 'languages' are incompatible.
        Type 'readonly string[]' is not assignable to type 'string | string[]'.
          The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.

108   create?(
      ~~~~~~


Found 1 error.
```

## Last working version

Worked up to version: 20.3.3

Stopped working in version: 20.3.4

## To Reproduce

Take a typescript project depending on `i18next` and `i18next-http-backend` and run the tsc command.

## Expected behavior

tsc shouldn't fail.

## Your Environment

- *runtime version*: node 14.17.3, tsc 4.3.4
- *i18next version*: 20.3.4
- *i18next-http-backend version*: 1.2.6
- *os*: Windows

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-http-backend/issues/73 -> PR welcome there

**Comment by adrai** [comment]
@pedrodurek

**Comment by pedrodurek** [comment]
I believe this was fixed, right?

**Comment by jamuhl** [comment]
yes
