### ISSUE TITLE
After updating to 13 changeLanguage does not work

### ISSUE THREAD

**Issue by 1Map** [i18next/i18next#1148]
After I updates to version 13 the changeLanguage gives the following error:

`TypeError: i18n.changeLanguage is not a function`

My code is (Note this use to work before 13):

```
const i18next = require('i18next');
const i18nextMiddleware = require('i18next-express-middleware');
const Backend = require('i18next-node-fs-backend');

const i18n = i18next
    .use(Backend)
    .use(i18nextMiddleware.LanguageDetector)
    .init({
        backend: {
            loadPath: path.join(__dirname, '/locales/{{lng}}/{{ns}}.json'),
            addPath: path.join(__dirname, '/locales/{{lng}}/{{ns}}.missing.json')
        },
        detection: {
            order: ['querystring', 'cookie'],
            caches: ['cookie']
        },
        fallbackLng: 'en',
        preload: ['en', 'de'],
        saveMissing: true
    });

/* Pug View engine setup */
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');

app.use(i18nextMiddleware.handle(i18next));

/* ERROR GIVEN HERE AS **TypeError: i18n.changeLanguage is not a function** */
i18n.changeLanguage(req.curLanguage, function(err, t) {
        if (err) return console.log('something went wrong loading', err);
});
```

**Comment by jamuhl** [comment]
guess this is related to: https://github.com/i18next/i18next/pull/1142

**Comment by jamuhl** [comment]
No same as: https://github.com/i18next/react-i18next/issues/646

For what do i write migration or changelog notes if no one reads them 😃

v13 -> migration guide: https://www.i18next.com/misc/migration-guide#v-12-x-x-to-v-13-0-0 or changelog: https://github.com/i18next/i18next/blob/master/CHANGELOG.md#1300

> promise API added for all functions providing a callback i18next/i18next#1130 -> means those will now return a Promise and not this -> so you can't chain eg. i18next.init().on() anylonger as init returns a Promise

```js
const i18n = i18next // nope i18n is a promise not an instance
```

**Comment by 1Map** [comment]
Thanks,

I changed:

`i18n.changeLanguage(req.curLanguage, function(err, t) {`

to

`i18next.changeLanguage(req.curLanguage, function(err, t) {`

and now it works
