### ISSUE TITLE
type errors when trying to access keys with similar names

### ISSUE THREAD

**Issue by adil-hublo** [i18next/i18next#2240]
## 🐛 Bug Report

Hello,

I am having trouble with the latest i18next version `23.15.1` which is not occurring in the version `23.15.0`.
When trying to access to a key in a namespace, if another key exists and begins with the same characters, the types are merged in a union type, and thus, typescript errors.
I tried with different typescript versions, they all errors; so I checked the PR done for the last version bump and I suspect it, as it's totally ts-related.

Thank you for everything :)

## To Reproduce

Here is an example of JSON source triggering the bug:
```js
"job": "Jobs",
"job_details": {
  "title": "sample test"
},
```

And here is the code triggering the error:

```js
label: t('profile.job') 
// error TS2322: Type 'string | { title: string }' is not assignable to type 'string'.
```

## Expected behavior

Type of `t('profile.job')` should be a string, according to the type extracted from the JSON file above.

## Your Environment

- *runtime version*: Node 20.16.0
- *i18next version*: 23.15.1

**Comment by adrai** [comment]
this was the only change: https://github.com/i18next/i18next/pull/2234
Can you confirm @marcalexiei ?

**Comment by adrai** [comment]
btw: _ is used as context separator or as plural suffix... so maybe also change that if you don't use these features... https://www.i18next.com/overview/typescript#custom-type-options

`contextSeparator: '__something_else__'`
`pluralSeparator: '__something_else__'`

**Comment by adil-hublo** [comment]
@adrai thanks for the fast feedback!

I tried to set another separator in the module augmentation of `i18next` like this, because I am not using the separators.

```
    pluralSeparator: '__plural__'
    contextSeparator: '__context__'
```
However, the bug still occurs in places where underscores `_` are used.

ATM, I am still forced to stay in the previous minor release `23.15.0`

**Comment by marcalexiei** [comment]
[As I already written in the PR](https://github.com/i18next/i18next/pull/2234#issuecomment-2341437182) this kind of issue is not introduced by #2234.

<img width="1444" alt="image" src="https://github.com/user-attachments/assets/78efbaf6-9566-4738-a1c3-092e987689f0">

Using 23.15.0 returns the same type returned in 23.15.1.

**Comment by adrai** [comment]
@adil-hublo please provide a minimal reproducible example repository we can use to investigate

**Comment by noahsettersten** [comment]
I'm seeing a similar issue on a project where 23.15.1 returns a similar union type, whereas 23.15.0 returns the expected `string` type.

@marcalexiei Your screenshot looks to be loading the translations from a `.ts` file. Could the types be resolved differently when loading the translations from a `.json` file?

**Comment by adrai** [comment]
> Could the types be resolved differently when loading the translations from a `.json` file?

You mean like [this](https://github.com/i18next/i18next/blob/master/examples/typescript/i18n/config.ts#L2)? => https://www.i18next.com/overview/typescript#not-working-interpolation-values

**Comment by noahsettersten** [comment]
Oh, sorry. In my case, this translations are loaded using [the HTTP backend](https://github.com/i18next/i18next-http-backend).

**Comment by marcalexiei** [comment]
> Your screenshot looks to be loading the translations from a .ts file. Could the types be resolved differently when loading the translations from a .json file?

Same behaviour expect the type is `string` instead of constant strings.

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/5aa3006f-aa5d-4a70-be69-e9ceb656f181">

> [!TIP]
> You can start to creating a minimal reproduction from here: https://github.com/i18next/i18next/tree/master/examples/typescript

**Comment by adrai** [comment]
> Oh, sorry. In my case, the translations are loaded using [the HTTP backend](https://github.com/i18next/i18next-http-backend).
> 
> We then have a `.d.ts` file that adds to the types that looks generally like this:
> 
> ```
> import "i18next";
> import ns from "../../namespace.json";
> 
> declare module "i18next" {
>   interface CustomTypeOptions {
>     resources: {
>       namespace: typeof ns;
>     };
>   }
> }
> ```

i18next-http-backend is only relevant on runtime... not relevant for TypeScript at all.. what counts is in your case: `import ns from "../../namespace.json";`

**Comment by adrai** [comment]
Have also a look at: https://github.com/locize/i18next-typescript-examples

**Comment by adil-hublo** [comment]
https://github.com/i18next/i18next/issues/2240#issuecomment-2361597411

in your example I see you are using `23.15.0` though, which is a totally fine version for me.

Here is a minimal reproduction example:

```js
import 'i18next'
import type mainWorker from '../assets/locales/en/main.worker.json'

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'main.worker'
    resources: {
      ['main.worker']: typeof mainWorker
    }
  }
}
```

The json extract (I stripped it, but tried like that and still reproduced the same error):

```js
{
"shift_acceptation_modal": {
    "alert": "test",
    "button": "test",
    "rules_title": "test",
    "title": "test"
  },
  "shift_application_modal": {
    "alert": "test",
    "application_button": "test",
    "explanation": "test",
    "multiple_specialties": "test",
    "rule_0": "test",
    "rule_0bis": "test",
    "rule_1": "test",
    "rule_2": "test",
    "rule_3": "test",
    "rule_4": "test"
  },
  "shift_cancel_modal": {
    "admin_section_deactivated": "test",
    "admin_section_email_button": "test",
    "title": "test"
  },
  "shift_cancellation": {
    "policy_page_abs_text1": "test",
    "policy_page_abs_text2": "test",
    "policy_page_abs_text3": "test",
    "policy_page_abs_title1": "test",
    "policy_page_title": "Cancellation Policy"
  },
  "shift_card_hourly_rate": "test",
  "shift_deal_modal": {
    "comment_placeholder": "Write a question, a need or any other request related to this mission.",
    "comment_title": "test",
    "title": "Apply"
  },
  "shift_details": {
    "add_to_calendar_link": "Add to calendar",
    "service_bed": "{{beds_capacity}} beds",
    "service_building": "Building {{building}}",
    "service_digicode": "Digicode {{digicode}}",
    "service_floor": "Floor {{floor}}",
    "service_free_parking": "Free parking",
    "service_meal_not_provided": "Meals not included",
    "service_meal_provided": "Meals available",
    "service_no_parking": "No parking",
    "service_outfit_not_provided": "Outfit not supplied",
    "service_outfit_provided": "Outfit provided",
    "service_paid_parking": "Paid parking",
    "service_section_title": "Service",
    "service_software": "test",
    "service_workers_per_shift": "test",
    "shift_duration": "Total duration: {{duration}}",
    "sign_dialog": "test",
    "success_message_download": "test",
    "tab_details": "Details",
    "tab_institution": "Facility",
    "title": "test"
  },
  "shift_refusal_modal": {
    "text": "test",
    "title": "test"
  },
  "shift": {
    "application_arrival_formalities_button": "test",
    "application_arrival_formalities_title": "test",
    "application_contact_title": "test",
    "application_link_arrival_formalities": "test",
    "application_progress_button": "test",
    "application_progress_message": "test",
    "application_progress_title": "test",
    "application_section_message_application_refused": "test",
    "application_section_message_in_process": "test",
    "success_message_apply": "test",
    "success_message_assign": "test"
  },
  "shifts": {
    "preferences_pool": "test"
  }
}

The keys erroring with an union type instead of type `string` only are the one in `shift_details` object, beginning with the letter `s`.
Changing the plural and context separator fixes the error I had at the beginning (`profile.job` key) but not those type errors

**Comment by adrai** [comment]
> [#2240 (comment)](https://github.com/i18next/i18next/issues/2240#issuecomment-2361597411)
> 
> in your example I see you are using `23.15.0` though, which is a totally fine version for me.
> 
> Here is a minimal reproduction example:
> 
> ```js
> import 'i18next'
> import type mainWorker from '../assets/locales/en/main.worker.json'
> 
> declare module 'i18next' {
>   interface CustomTypeOptions {
>     defaultNS: 'main.worker'
>     resources: {
>       ['main.worker']: typeof mainWorker
>     }
>   }
> }
> ```
> 
> The json extract (I stripped it, but tried like that and still reproduced the same error):
> 
> ```js
> {
> "shift_acceptation_modal": {
>     "alert": "test",
>     "button": "test",
>     "rules_title": "test",
>     "title": "test"
>   },
>   "shift_application_modal": {
>     "alert": "test",
>     "application_button": "test",
>     "explanation": "test",
>     "multiple_specialties": "test",
>     "rule_0": "test",
>     "rule_0bis": "test",
>     "rule_1": "test",
>     "rule_2": "test",
>     "rule_3": "test",
>     "rule_4": "test"
>   },
>   "shift_cancel_modal": {
>     "admin_section_deactivated": "test",
>     "admin_section_email_button": "test",
>     "title": "test"
>   },
>   "shift_cancellation": {
>     "policy_page_abs_text1": "test",
>     "policy_page_abs_text2": "test",
>     "policy_page_abs_text3": "test",
>     "policy_page_abs_title1": "test",
>     "policy_page_title": "Cancellation Policy"
>   },
>   "shift_card_hourly_rate": "test",
>   "shift_deal_modal": {
>     "comment_placeholder": "Write a question, a need or any other request related to this mission.",
>     "comment_title": "test",
>     "title": "Apply"
>   },
>   "shift_details": {
>     "add_to_calendar_link": "Add to calendar",
>     "service_bed": "{{beds_capacity}} beds",
>     "service_building": "Building {{building}}",
>     "service_digicode": "Digicode {{digicode}}",
>     "service_floor": "Floor {{floor}}",
>     "service_free_parking": "Free parking",
>     "service_meal_not_provided": "Meals not included",
>     "service_meal_provided": "Meals available",
>     "service_no_parking": "No parking",
>     "service_outfit_not_provided": "Outfit not supplied",
>     "service_outfit_provided": "Outfit provided",
>     "service_paid_parking": "Paid parking",
>     "service_section_title": "Service",
>     "service_software": "test",
>     "service_workers_per_shift": "test",
>     "shift_duration": "Total duration: {{duration}}",
>     "sign_dialog": "test",
>     "success_message_download": "test",
>     "tab_details": "Details",
>     "tab_institution": "Facility",
>     "title": "test"
>   },
>   "shift_refusal_modal": {
>     "text": "test",
>     "title": "test"
>   },
>   "shift": {
>     "application_arrival_formalities_button": "test",
>     "application_arrival_formalities_title": "test",
>     "application_contact_title": "test",
>     "application_link_arrival_formalities": "test",
>     "application_progress_button": "test",
>     "application_progress_message": "test",
>     "application_progress_title": "test",
>     "application_section_message_application_refused": "test",
>     "application_section_message_in_process": "test",
>     "success_message_apply": "test",
>     "success_message_assign": "test"
>   },
>   "shifts": {
>     "preferences_pool": "test"
>   }
> }
> 
> The keys erroring with an union type instead of type `string` only are the one in `shift_details` object, beginning with the letter `s`.
> Changing the plural and context separator fixes the error I had at the beginning (`profile.job` key) but not those type errors
> ```

@adil-hublo you're still pasting some code snippets... Please create a new github repository and put this stuff into there, with a valid package.json pointing to the newest i18next version

**Comment by noahsettersten** [comment]
FYI: This looks to be fixed now for me now that I've upgraded 23.16.5! This was possibly resolved by 23.15.2 (from https://github.com/i18next/i18next/pull/2243).

**Comment by adrai** [comment]
stale... so closing for now...
