### ISSUE TITLE
error TS2322: Type 'DefaultTFuncReturn' is not assignable to type 'string'

### ISSUE THREAD

**Issue by DavidArmendariz** [i18next/i18next#1874]
## 💥 Regression Report

We cannot upgrade to i18next from 22.0.2 to 22.0.6 because the `t` function does not return a string anymore.

## Last working version

Worked up to version: 22.0.2

Stopped working in version: 22.0.6

## To Reproduce

```js
<div aria-label={t('Example')}></div>
```

The above won't work because `t` returns `DefaultTFuncReturn` instead of `string`

## Expected behavior

```js
<div aria-label={t('Example')}></div>
```

Should work

## Your Environment

- *runtime version*: node v18
- *i18next version*: 22.0.2
- *os*: Linux

**Comment by adrai** [comment]
fyi: https://github.com/i18next/react-i18next/issues/1587#issuecomment-1328676628

**Comment by newilu** [comment]
still not working with nextjs 13.



react-i18next.d.ts:
`declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: I18nNamespaces;
    returnNull: false;
  }
}`

**Comment by adrai** [comment]
it's i18next not react-i18next...
compare with this: https://github.com/i18next/next-i18next/blob/master/examples/simple/%40types/i18next.d.ts

**Comment by OZZlE** [comment]
Why is this ticket closed, it's still an issue?

**Comment by taxilian** [comment]
It's closed because there is an explanation / fix linked above.

see https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

**Comment by OZZlE** [comment]
> It's closed because there is an explanation / fix linked above.
> 
> see https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

ok from my testing it never returns null though... I didn't define any translation at all, not even in the default language it still does NOT return null... so the type is just wrong?

**Comment by jamuhl** [comment]
you can set translations to `null` -> therefore `t` can return null

https://www.i18next.com/overview/configuration-options#translation-defaults -> returnNull

**Comment by marcus-sa** [comment]
> It's closed because there is an explanation / fix linked above.
> 
> see [i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz](https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz)

That doesn't fix it ...

**Comment by taxilian** [comment]
> That doesn't fix it ...

if you're going to complain that something didn't work I would strongly suggest that you be specific. What exactly doesn't fix it? What did you try?

To me the explanation was sufficient for me to understand that "this isn't actually a bug because null is a valid return type" and to realize that I can fix it by just adding a `!` after it, but there are also instructions on how to create  .d.ts file in your project which overrides it to remove `null` as a return type. Did you try that?

Nobody can help you without details, so saying "that doesn't fix it" is essentially just complaining without actually providing the ability for anyone to help. I'm not involved with this project, but I'd still be happy to help someone with some basic troubleshooting... if they provided enough information for that to be a possibility, which you haven't.
